apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: fnd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: iam-secret
                  key: IAM_USERNAME
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iam-secret
                  key: IAM_PASSWORD
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: fnd
spec:
  selector:
    app: keycloak
  ports:
    - port: 8180        # external port
      targetPort: 8080  # container port inside pod
  type: LoadBalancer
