apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"keycloak","namespace":"fnd"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"keycloak"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-08-24T19:47:23Z"
  name: keycloak
  namespace: fnd
  resourceVersion: "397984"
  uid: 501e8082-23c6-4945-81bd-5d631d2a6dec
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.167.55
  clusterIPs:
  - 10.105.167.55
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32082
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: keycloak
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
      ipMode: VIP
