apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: fnd
  labels:
    app: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.5
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - export KRAKEND_LISTEN_ADDRESS="0.0.0.0:8080";
              exec krakend run -c /etc/krakend/krakend.json
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
          readinessProbe:
            httpGet:
              path: /__health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /__health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
---
apiVersion: v1
kind: Service
metadata:
  name: krakend
  namespace: fnd
  labels:
    app: krakend
spec:
  selector:
    app: krakend
  ports:
    - protocol: TCP
      port: 8380        # external service port you’ll call
      targetPort: 8080  # container port KrakenD listens on
  type: LoadBalancer
