apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: fnd
  labels:
    app: krakend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.7.2
          args: ["run", "-c", "/etc/krakend/krakend.json", "-d"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
