apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: fnd
data:
  krakend.json: |
    {
      "version": 3,
      "name": "FoodnDeliv API Gateway",
      "port": 8080,
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "telemetry/logging": { "level": "DEBUG" },

      "endpoints": [
        {
          "endpoint": "/api/orders/{username}",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/api/orders/{username}",
              "host": ["http://foodndeliv:8080"]
            }
          ],
          "extra_config": {
            "github.com/devopsfaith/krakend-jose/validator": {
              "alg": "RS256",
              "jwk-url": "http://keycloak.fnd.svc.cluster.local:8180/realms/fnd/protocol/openid-connect/certs",
              "issuer": "http://keycloak:8180/realms/fnd",
              "disable_jwk_security": true,
              "disable_audience_validation": true,
              "cache": true,
              "operation_debug": true,
              "roles_key": "realm_access.roles",
              "roles": ["admin", "customer"]
            },
            "validation/cel": {
              "expressions": [
                {
                  "check_expr": "jwt.claims.preferred_username == request.params.username || has(jwt.claims['realm_access'].roles, 'admin')",
                  "error": "forbidden: wrong user"
                }
              ]
            }
          }
        },
        {
          "endpoint": "/api/deliveries",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/api/deliveries",
              "host": ["http://foodndeliv:8080"]
            }
          ],
          "extra_config": {
            "auth/introspection": {
              "endpoint": "http://keycloak.fnd.svc.cluster.local:8180/realms/fnd/protocol/openid-connect/token/introspect",
              "client_id": "foodndeliv-api",
              "client_secret": "LGMw1izQHxxxCO82En83idRAImLtdWDt",
              "cache": true,
              "operation_debug": true
            }
          }
        }
      ]
    }
