apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fnd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-app-secret
            - configMapRef:
                name: db-config
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fnd
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
